name: Container Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.timestamp.outputs.timestamp }}
      image-digest: ${{ steps.build.outputs.digest }}
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Generate timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=${{ steps.timestamp.outputs.timestamp }},enable={{is_default_branch}}

    - name: Build Docker image
      id: build
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        outputs: type=docker,dest=/tmp/image.tar

    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: /tmp/image.tar
        retention-days: 1

  push:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        path: /tmp

    - name: Load Docker image
      run: docker load --input /tmp/image.tar

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=${{ needs.build.outputs.image-tag }},enable={{is_default_branch}}

    - name: Push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  trigger-cd:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    needs: [build, push]
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Update deployment repository
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_REPO_TOKEN }}
        DEPLOY_REPO: hustshawn/k8s-deploy-demo
        IMAGE_TAG: ${{ needs.build.outputs.image-tag }}
      run: |
        # Clone the deployment repository with token authentication
        git clone https://$GITHUB_TOKEN@github.com/$DEPLOY_REPO.git deploy-repo
        cd deploy-repo
        
        # Configure git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Create a new branch for the update
        BRANCH_NAME="update-image-tag-$IMAGE_TAG"
        git checkout -b $BRANCH_NAME
        
        # Update the image tag in kustomization.yaml using Kustomize image override
        # Current format: newTag: main -> newTag: TIMESTAMP
        sed -i "s|newTag: .*|newTag: $IMAGE_TAG|g" kustomization.yaml
        
        # Verify the change was made
        echo "Updated kustomization.yaml:"
        grep -A 2 "images:" kustomization.yaml
        
        # Check if there are any changes
        if git diff --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Show the diff for debugging
        echo "Changes made:"
        git diff
        
        # Commit and push changes
        git add kustomization.yaml
        git commit -m "Update image tag to $IMAGE_TAG

        - Updated hustshawn/k8s-demo image tag from main to $IMAGE_TAG via Kustomize
        - Source commit: ${{ github.sha }}
        - Triggered by: ${{ github.event_name }} on ${{ github.ref }}"
        
        # Set remote URL with token for pushing
        git remote set-url origin https://$GITHUB_TOKEN@github.com/$DEPLOY_REPO.git
        git push origin $BRANCH_NAME
        
        # Create pull request using GitHub CLI
        gh pr create \
          --title "🚀 Update image tag to $IMAGE_TAG" \
          --body "## Automated Deployment Update

        This PR updates the container image tag using Kustomize image override.

        ### Changes
        - **Image**: \`hustshawn/k8s-demo:main\` → \`hustshawn/k8s-demo:$IMAGE_TAG\`
        - **File**: \`kustomization.yaml\`
        - **Method**: Kustomize image override
        - **Timestamp**: $IMAGE_TAG
        - **Source Commit**: [\`${{ github.sha }}\`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

        ### Deployment Details
        - **Namespace**: default
        - **App**: backend-app
        - **Container**: backend

        ### Kustomize Configuration
        \`\`\`yaml
        images:
        - name: hustshawn/k8s-demo
          newTag: $IMAGE_TAG
        \`\`\`

        ---
        🤖 This PR was automatically created by the CI/CD pipeline." \
          --head $BRANCH_NAME \
          --base main
